---
  - name: Create json files from template
    template:
      src: "./roles/{{role}}/templates/tenant_and_anp.j2"
      dest: "./roles/{{role}}/files/tenant_and_anp_S{{ item }}.json"
    with_items: "{{ STUDENTS }}"
   
  - name: Post json files to APIC
    aci_rest:
      host: "{{ APIC }}"
      username: "{{ USERNAME }}"
      password: "{{ PASSWORD }}"
      uri: "/api/node/mo/uni/tn-S{{ item }}.json"
      config_file: "./roles/{{role}}/files/tenant_and_anp_S{{ item }}.json"
      action: "post"
      protocol: https
    with_items: "{{ STUDENTS }}"
