---
  - name: Create json files from template
    template:
      src: "./roles/{{role}}/templates/vmm_to_aep.j2"
      dest: "./roles/{{role}}/files/vmm_to_aep_S{{ item }}.json"
    with_items: "{{ STUDENTS }}"
   
  - name: Post json files to APIC
    aci_rest:
      host: "{{ APIC }}"
      username: "{{ USERNAME }}"
      password: "{{ PASSWORD }}"
      uri: "/api/node/mo/uni/infra/attentp-AEP-Training-VMM-Class{{ CLASS_NBR }}.json"
      config_file: "./roles/{{role}}/files/vmm_to_aep_S{{ item }}.json"
      action: "post"
      protocol: https
    with_items: "{{ STUDENTS }}"
